version: '3.1'

services:
    # --------------------------------------------------------------
    #
    #   Openvidu-Call Version: 2.24.0
    #
    # --------------------------------------------------------------
    app:
#        image: openvidu/openvidu-call:2.24.0
        build:
            context: github 
            dockerfile: ./docker/Dockerfile.node
        restart: on-failure
        network_mode: host
        environment:
            - SERVER_PORT=5442
            - OPENVIDU_URL=http://localhost:5443
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
            - CALL_OPENVIDU_CERTTYPE=${CERTIFICATE_TYPE}
            - CALL_PRIVATE_ACCESS=${CALL_PRIVATE_ACCESS:-}
            - CALL_USER=${CALL_USER:-}
            - CALL_SECRET=${CALL_SECRET:-}
            - CALL_ADMIN_SECRET=${CALL_ADMIN_SECRET:-}
            - CALL_RECORDING=${CALL_RECORDING:-}
        env_file:
            - .env
        logging:
            options:
                max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
